CREATE TABLE Visitor (
    ID int IDENTITY(1,1),
    IP_ADDRESS VARCHAR(45),
    COUNTRY_NAME VARCHAR(41), -- based on the longest possible name according to google.
    REGION_NAME VARCHAR(41),
    CITY VARCHAR (41),
    LATITUDE DECIMAL (9,5),
    LONGITUDE DECIMAL (9,5),
    INSERT_DATE DATETIME2 (3) CONSTRAINT DF_Visitor_INSERT_DATE DEFAULT (SYSDATETIME()),
    UPDATE_DATE DATETIME2 (3),
    UPDATE_COUNT INTEGER INT NOT NULL DEFAULT(0)
)