CREATE TABLE Visitor (
    ID int IDENTITY(1,1),
    IP_ADDRESS VARCHAR(45),
    COUNTRY_NAME VARCHAR(41), -- based on the longest possible name according to google.
    REGION_NAME VARCHAR(41),
    CITY VARCHAR (41),
    LATITUDE DECIMAL (9,5),
    LONGITUDE DECIMAL (9,5),
    INSERT_DATE DATETIME,
    UPDATE_DATE DATETIME NULL
)